<a href="https://colab.research.google.com/github/anushka-code/Feature-Envy-Code-Smell-Classification/blob/main/Feature_Envy_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Left Branch of the NN-Architecture : CNN for Structural Object Oriented Metrics Feature Extraction





###Mounting Google Drive

In [2]:
!pip install -U -q PyDrive

In [3]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
    
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [4]:
import numpy as np
import pandas as pd

Long Parameters Dataset

In [5]:
link = 'https://drive.google.com/file/d/1EfbAqgr7i9h4yFwEoU3igG34Gt48l6WT/view?usp=sharing'
  
# to get the id part of the file
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('long_parameters_list_structural.csv')  
  
df_lp = pd.read_csv('long_parameters_list_structural.csv')
df_lp.head(5)

NOP_method  CC_method  ... LOC_project is_long_parameters_list
0           0          0  ...       65687                   False
1           0          0  ...       65687                   False
2           1          0  ...       65687                   False
3           0          5  ...       65687                   False
4           1          0  ...       65687                   False

[5 rows x 57 columns]

Switch Statements Dataset

In [20]:
link= 'https://drive.google.com/file/d/1Ya1OMWsz1yyXAaZheIck-roX0M9UWiqg/view?usp=sharing'
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('switch_statements_structural.csv')  
  
df_ss = pd.read_csv('switch_statements_structural.csv')
df_ss.head(5)

NOP_method  CC_method  ... LOC_project is_switch_statements
0           1          2  ...       65687                False
1           0          0  ...       65687                False
2           2          0  ...       65687                False
3           0          0  ...       65687                False
4           0          0  ...       65687                False

[5 rows x 57 columns]

### Data Pre-Processing of the Code Smell Datasets

In [15]:
import numpy as np
df_lp.rename(columns = {'is_long_parameters_list':'is_code_smell'}, inplace = True)
df_lp["is_code_smell"] = df_lp["is_code_smell"].astype(int)
Y_lp = df_lp.iloc[:,-1:]
X_lp = df_lp.iloc[:,:82]
X_lp = X_lp.replace(to_replace =["?"], value = np.nan)
X_lp = X_lp.astype(float)

In [25]:
X_lp.head(5)

NOP_method  CC_method  ...  LOC_project  is_code_smell
0         0.0        0.0  ...      65687.0            0.0
1         0.0        0.0  ...      65687.0            0.0
2         1.0        0.0  ...      65687.0            0.0
3         0.0        5.0  ...      65687.0            0.0
4         1.0        0.0  ...      65687.0            0.0

[5 rows x 57 columns]

In [26]:
Y_lp.head(5)

is_code_smell
0              0
1              0
2              0
3              0
4              0

In [29]:
X_lp.shape

(420, 57)

In [30]:
Y_lp.shape

(420, 1)

In [21]:
import numpy as np
df_ss.rename(columns = {'is_switch_statements':'is_code_smell'}, inplace = True)
df_ss["is_code_smell"] = df_ss["is_code_smell"].astype(int)
Y_ss = df_ss.iloc[:,-1:]
X_ss = df_ss.iloc[:,:82]
X_ss = X_ss.replace(to_replace =["?"], value = np.nan)
X_ss = X_ss.astype(float)

In [23]:
X_ss.head(5)

NOP_method  CC_method  ...  LOC_project  is_code_smell
0         1.0        2.0  ...      65687.0            0.0
1         0.0        0.0  ...      65687.0            0.0
2         2.0        0.0  ...      65687.0            0.0
3         0.0        0.0  ...      65687.0            0.0
4         0.0        0.0  ...      65687.0            0.0

[5 rows x 57 columns]

In [24]:
Y_ss.head(5)

is_code_smell
0              0
1              0
2              0
3              0
4              0

In [32]:
X_ss.shape

(420, 57)

In [33]:
Y_ss.shape

(420, 1)

### Concatenating the Datasets

In [35]:
import pandas as pd
code_smells = [X_lp, X_ss]
X_train = pd.concat(code_smells)
type(X_train)

pandas.core.frame.DataFrame

In [37]:
X_train.shape

(840, 57)

In [38]:
import pandas as pd
labels = [Y_lp, Y_ss]
Y_train = pd.concat(labels)
type(Y_train)

pandas.core.frame.DataFrame

In [39]:
Y_train.shape

(840, 1)

In [51]:
Y_train['is_code_smell'].value_counts()

0    573
1    267
Name: is_code_smell, dtype: int64

###SMOTE's Algorithm - For Oversampling


###Data Normalization

In [47]:
from sklearn.preprocessing import MinMaxScaler
# compute required values
scaler = MinMaxScaler()
model = scaler.fit(X_train)
X_train = model.transform(X_train)
print(X_train)
X_train.shape

[[0.         0.         0.         ... 0.3325772  0.19318279 0.        ]
 [0.         0.         0.         ... 0.3325772  0.19318279 0.        ]
 [0.0625     0.         0.         ... 0.3325772  0.19318279 0.        ]
 ...
 [0.0625     0.         0.09638554 ... 0.62322552 1.         1.        ]
 [0.0625     0.         0.06024096 ... 0.62322552 1.         1.        ]
 [0.125      0.15789474 0.13253012 ... 0.62322552 1.         1.        ]]


(840, 57)

In [49]:
X_train_final = X_train.reshape((840,57,1))

### 1-D CNN Implementation

In [52]:
import pandas as pd
import numpy as np
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Input, Convolution1D, MaxPooling1D, Flatten, Dense, Dropout
from keras.utils import np_utils

In [54]:
model = Sequential()
model.add(Convolution1D(filters=128, kernel_size=3, activation='relu', input_shape=(57,1)))
model.add(Convolution1D(filters=128, kernel_size=3, activation='relu'))
model.add(Dropout(0.25))
model.add(MaxPooling1D(pool_size=2))
model.add(Convolution1D(filters=128, kernel_size=5, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

#check pretrained models for feature extraction of CNN 2d data 
#which is good for numerical data
#modelfit xd boost (better version)
#imbalanced data - synthetic data addition 
#random forest

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_3 (Conv1D)           (None, 55, 128)           512       
                                                                 
 conv1d_4 (Conv1D)           (None, 53, 128)           49280     
                                                                 
 dropout_1 (Dropout)         (None, 53, 128)           0         
                                                                 
 max_pooling1d_2 (MaxPooling  (None, 26, 128)          0         
 1D)                                                             
                                                                 
 conv1d_5 (Conv1D)           (None, 22, 128)           82048     
                                                                 
 max_pooling1d_3 (MaxPooling  (None, 11, 128)          0         
 1D)                                                  

In [58]:
hist = model.fit(X_train_final,Y_train,epochs=20,shuffle=True,batch_size=50,validation_split=0.10) 

Epoch 1/20
16/16 [==============================] - 1s 51ms/step - loss: nan - accuracy: 0.6839 - val_loss: nan - val_accuracy: 0.6667
Epoch 2/20
16/16 [==============================] - 1s 48ms/step - loss: nan - accuracy: 0.6839 - val_loss: nan - val_accuracy: 0.6667
Epoch 3/20
16/16 [==============================] - 1s 47ms/step - loss: nan - accuracy: 0.6839 - val_loss: nan - val_accuracy: 0.6667
Epoch 4/20
16/16 [==============================] - 1s 48ms/step - loss: nan - accuracy: 0.6839 - val_loss: nan - val_accuracy: 0.6667
Epoch 5/20
16/16 [==============================] - 1s 49ms/step - loss: nan - accuracy: 0.6839 - val_loss: nan - val_accuracy: 0.6667
Epoch 6/20
16/16 [==============================] - 1s 48ms/step - loss: nan - accuracy: 0.6839 - val_loss: nan - val_accuracy: 0.6667
Epoch 7/20
16/16 [==============================] - 1s 48ms/step - loss: nan - accuracy: 0.6839 - val_loss: nan - val_accuracy: 0.6667
Epoch 8/20
16/16 [==============================] - 1s 

###Forming Groups of Features 

Make one-hot encoded data for project, package, class and method groups

*   0 : method
*   1 : class
*   2 : package
*   3 : project





In [59]:
group_of_features = {
    "NOP_method" : 0,
    "CC_method" : 0,
    "ATFD_method" : 0,
    "FDP_method" : 0,
    "CM_method" : 0,
    "MAXNESTING_method" : 0,
    "LOC_method" : 0,
    "CYCLO_method" : 0,
    "NMCS_method" : 0,
    "NOLV_method" : 0,
    "MaMCL_method" : 0,
    "NOAV_method" : 0,
    "LAA_method" : 0,
    "FANOUT_method" : 0,
    "CFNAMM_method" : 0,
    "ATLD_method" : 0,
    "CLNAMM_method" : 0,
    "CINT_method" : 0,
    "MeMCL_method" : 0,
    "CDISP_method" : 0,
    "NOII_type" : 1,
    "NOAM_type" : 1,
    "NOCS_type" : 2,
    "NOM_type" : 1,
    "NMO_type" : 1,
    "ATFD_type" : 0,
    "FANOUT_type" : 1,
    "NOMNAMM_type" : 1,
    "NOA_type" : 1,
    "NIM_type" : 1,
    "DIT_type" : 1,
    "LOC_type" : 1,
    "LOCNAMM_type" : 1,
    "CFNAMM_type" : 1,
    "TCC_type" : 0,
    "NOPA_type" : 1,
    "CBO_type" : 1,
    "RFC_type" : 1,
    "NOC_type" : 1,
    "WMC_type" : 1,
    "LCOM5_type" : 0,
    "WOC_type" : 0,
    "WMCNAMM_type" : 1,
    "AMW_type" : 1,
    "AMWNAMM_type" : 1,
    "NOCS_package" : 2,
    "NOMNAMM_package" : 2,
    "NOI_package" : 2,
    "LOC_package" : 2,
    "NOM_package" : 2,
    "NOPK_project" : 3,
    "NOCS_project" : 3,
    "NOI_project" : 3,
    "NOM_project" : 3,
    "NOMNAMM_project" : 3,
    "LOC_project" : 3,
    "isStatic_type" : 1,
    "number_private_visibility_attributes" : 1,
    "number_protected_visibility_attributes" : 1,
    "number_package_visibility_attributes" : 1,
    "num_final_attributes" : 1,
    "num_static_attributes" : 1,
    "num_final_static_attributes" : 1,
    "num_not_final_not_static_attributes" : 1,
    "num_final_not_static_attributes" : 1,
    "num_static_not_final_attributes" : 1,
    "number_public_visibility_methods" : 0,
    "number_private_visibility_methods" : 0,
    "number_protected_visibility_methods" : 0,
    "number_package_visibility_methods" : 0,
    "number_final_methods" : 0,
    "number_abstract_methods" : 0,
    "number_not_abstract_not_final_methods" : 0,
    "number_static_methods" : 0,
    "number_final_static_methods" : 0,
    "number_final_not_static_methods" : 0,
    "number_not_final_static_methods" : 0,
    "number_not_final_not_static_methods" : 0,
    "number_standard_design_methods" : 0,
    "number_constructor_DefaultConstructor_methods" : 0,
    "number_constructor_NotDefaultConstructor_methods" : 0,
    "isStatic_method" : 0
}

print(len(group_of_features.keys()))

82


In [60]:
from collections import Counter
res = Counter(group_of_features.values())
print(res)

#hence we have methods = 40, class = 30, project = 6, package = 6

Counter({0: 40, 1: 30, 2: 6, 3: 6})


In [61]:
from keras.utils import np_utils
group_type = np.fromiter(group_of_features.values(), dtype=float)
group_type_one_hot = np_utils.to_categorical(group_type, dtype=float)
print(group_type_one_hot)
print(group_type_one_hot.shape)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0.

###Data Reshaping

In [ ]:
c = np.array([1,2,3,4])
x = np.tile(c,(4,1))
print(x)
x.shape

In [ ]:
group_type_one_hot_reshaped = group_type_one_hot.reshape(1,82,4)

In [ ]:
sample = np.tile(group_type_one_hot_reshaped,(715,1,1))
print(sample)
sample.shape

In [ ]:
new = X_train.reshape((715,82,1))
new.shape

In [ ]:
X_train_inter = np.dstack((new, sample))
X_train_inter.shape

In [ ]:
model = Sequential()
model.add(Convolution1D(filters=128, kernel_size=3, activation='relu', input_shape=(82,5)))
model.add(Convolution1D(filters=128, kernel_size=3, activation='relu'))
model.add(Dropout(0.25))
model.add(MaxPooling1D(pool_size=2))
model.add(Convolution1D(filters=128, kernel_size=5, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

In [ ]:
hist = model.fit(X_train_inter,Y,epochs=50,shuffle=True,batch_size=100,validation_split=0.20) 