<a href="https://colab.research.google.com/github/anushka-code/Feature-Envy-Code-Smell-Classification/blob/main/Feature_Envy_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Left Branch of the NN-Architecture : CNN for Structural Object Oriented Metrics Feature Extraction





### Loading the Dataset from Google Drive

In [ ]:
!pip install -U -q PyDrive

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
    
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
link = 'https://drive.google.com/file/d/1bnQ_b524o2XqHSaILYhqzec39ZpGJ_Kc/view?usp=sharing'
  
# to get the id part of the file
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('feature_envy_classification.csv')  
  
df = pd.read_csv('feature_envy_classification.csv')
df.head(5)

id  NOP_method  ...  isStatic_method  is_feature_envy
0   1           0  ...                0            False
1   2           0  ...                0            False
2   3           0  ...                0            False
3   4           0  ...                0            False
4   5           1  ...                0            False

[5 rows x 84 columns]

### Data Pre-Processing

In [ ]:
df["is_feature_envy"] = df["is_feature_envy"].astype(int)

In [ ]:
df.head(5)

id  NOP_method  ...  isStatic_method  is_feature_envy
0   1           0  ...                0                0
1   2           0  ...                0                0
2   3           0  ...                0                0
3   4           0  ...                0                0
4   5           1  ...                0                0

[5 rows x 84 columns]

In [ ]:
df.shape

(715, 84)

In [ ]:
del df['id']

In [78]:
Y = df.iloc[:,-1:]
X = df.iloc[:,:82]
print(Y)

     is_feature_envy
0                  0
1                  0
2                  0
3                  0
4                  0
..               ...
710                0
711                0
712                1
713                0
714                0

[715 rows x 1 columns]


In [ ]:
import numpy as np
np.unique(Y,return_counts=True) # 1/5th are smelly & 4/5th are non smelly

(array([0, 1]), array([575, 140]))

In [ ]:
import numpy as np
X = X.replace(to_replace =["?"], value = np.nan) # replacing missing values with null values 

In [ ]:
X = X.astype(float)# converting all datatypes to float

In [ ]:
X.head(5)

NOP_method  ...  isStatic_method
0         0.0  ...              0.0
1         0.0  ...              0.0
2         0.0  ...              0.0
3         0.0  ...              0.0
4         1.0  ...              0.0

[5 rows x 82 columns]

In [ ]:
X.describe()

NOP_method  ...  isStatic_method
count  715.000000  ...       715.000000
mean     2.004196  ...         0.132867
std      2.721166  ...         0.339669
min      0.000000  ...         0.000000
25%      0.000000  ...         0.000000
50%      1.000000  ...         0.000000
75%      3.000000  ...         0.000000
max     29.000000  ...         1.000000

[8 rows x 82 columns]

###Data Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# compute required values
scaler = MinMaxScaler()
model = scaler.fit(X)
X_train = model.transform(X)
X_train.shape

(715, 82)

###Forming Groups of Features 

Make one-hot encoded data for project, package, class and method groups

*   0 : method
*   1 : class
*   2 : package
*   3 : project





In [ ]:
group_of_features = {
    "NOP_method" : 0,
    "CC_method" : 0,
    "ATFD_method" : 0,
    "FDP_method" : 0,
    "CM_method" : 0,
    "MAXNESTING_method" : 0,
    "LOC_method" : 0,
    "CYCLO_method" : 0,
    "NMCS_method" : 0,
    "NOLV_method" : 0,
    "MaMCL_method" : 0,
    "NOAV_method" : 0,
    "LAA_method" : 0,
    "FANOUT_method" : 0,
    "CFNAMM_method" : 0,
    "ATLD_method" : 0,
    "CLNAMM_method" : 0,
    "CINT_method" : 0,
    "MeMCL_method" : 0,
    "CDISP_method" : 0,
    "NOII_type" : 1,
    "NOAM_type" : 1,
    "NOCS_type" : 2,
    "NOM_type" : 1,
    "NMO_type" : 1,
    "ATFD_type" : 0,
    "FANOUT_type" : 1,
    "NOMNAMM_type" : 1,
    "NOA_type" : 1,
    "NIM_type" : 1,
    "DIT_type" : 1,
    "LOC_type" : 1,
    "LOCNAMM_type" : 1,
    "CFNAMM_type" : 1,
    "TCC_type" : 0,
    "NOPA_type" : 1,
    "CBO_type" : 1,
    "RFC_type" : 1,
    "NOC_type" : 1,
    "WMC_type" : 1,
    "LCOM5_type" : 0,
    "WOC_type" : 0,
    "WMCNAMM_type" : 1,
    "AMW_type" : 1,
    "AMWNAMM_type" : 1,
    "NOCS_package" : 2,
    "NOMNAMM_package" : 2,
    "NOI_package" : 2,
    "LOC_package" : 2,
    "NOM_package" : 2,
    "NOPK_project" : 3,
    "NOCS_project" : 3,
    "NOI_project" : 3,
    "NOM_project" : 3,
    "NOMNAMM_project" : 3,
    "LOC_project" : 3,
    "isStatic_type" : 1,
    "number_private_visibility_attributes" : 1,
    "number_protected_visibility_attributes" : 1,
    "number_package_visibility_attributes" : 1,
    "num_final_attributes" : 1,
    "num_static_attributes" : 1,
    "num_final_static_attributes" : 1,
    "num_not_final_not_static_attributes" : 1,
    "num_final_not_static_attributes" : 1,
    "num_static_not_final_attributes" : 1,
    "number_public_visibility_methods" : 0,
    "number_private_visibility_methods" : 0,
    "number_protected_visibility_methods" : 0,
    "number_package_visibility_methods" : 0,
    "number_final_methods" : 0,
    "number_abstract_methods" : 0,
    "number_not_abstract_not_final_methods" : 0,
    "number_static_methods" : 0,
    "number_final_static_methods" : 0,
    "number_final_not_static_methods" : 0,
    "number_not_final_static_methods" : 0,
    "number_not_final_not_static_methods" : 0,
    "number_standard_design_methods" : 0,
    "number_constructor_DefaultConstructor_methods" : 0,
    "number_constructor_NotDefaultConstructor_methods" : 0,
    "isStatic_method" : 0
}

print(len(group_of_features.keys()))

82


In [ ]:
from keras.utils import np_utils
group_type = np.fromiter(group_of_features.values(), dtype=float)
group_type_one_hot = np_utils.to_categorical(group_type, dtype=float)
print(group_type_one_hot)
print(group_type_one_hot.shape)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0.

###Data Reshaping

In [ ]:
c = np.array([1,2,3,4])
x = np.tile(c,(4,1))
print(x)
x.shape

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


(4, 4)

In [ ]:
group_type_one_hot_reshaped = group_type_one_hot.reshape(1,82,4)

In [75]:
sample = np.tile(group_type_one_hot_reshaped,(715,1,1))
print(sample)
sample.shape

[[[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]]


(715, 82, 4)

Three CNN layers whose setting is
filters = 128, kernel size = 1 and activation = tanh

In [76]:
new = X_train.reshape((715,82,1))
new.shape

(715, 82, 1)

In [89]:
X_train_inter = np.dstack((new, sample))
X_train_inter.shape

(715, 82, 5)